// <auto-generated />
using System;
using Bug_Tracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bug_Tracker.Migrations
{
    [DbContext(typeof(BugTrackerDBContext))]
    partial class BugTrackerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bug_Tracker.Models.Comment", b =>
                {
                    b.Property<Guid>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IssuesPost_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.HasIndex("IssuesPost_id");

                    b.HasIndex("user_id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Bug_Tracker.Models.Issue", b =>
                {
                    b.Property<Guid>("Post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Asigned_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Completed_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("Project_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Project_id1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Post_id");

                    b.HasIndex("Project_id1");

                    b.HasIndex("user_id");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Bug_Tracker.Models.Project", b =>
                {
                    b.Property<Guid>("Project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Project_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Project_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Bug_Tracker.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Project_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("user_id");

                    b.HasIndex("Project_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bug_Tracker.Models.Comment", b =>
                {
                    b.HasOne("Bug_Tracker.Models.Issue", "Issues")
                        .WithMany()
                        .HasForeignKey("IssuesPost_id");

                    b.HasOne("Bug_Tracker.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("user_id");

                    b.Navigation("Issues");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bug_Tracker.Models.Issue", b =>
                {
                    b.HasOne("Bug_Tracker.Models.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("Project_id1");

                    b.HasOne("Bug_Tracker.Models.User", "User")
                        .WithMany("Issues")
                        .HasForeignKey("user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bug_Tracker.Models.User", b =>
                {
                    b.HasOne("Bug_Tracker.Models.Project", null)
                        .WithMany("Users")
                        .HasForeignKey("Project_id");
                });

            modelBuilder.Entity("Bug_Tracker.Models.Project", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Bug_Tracker.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
